# Generated by Django 5.2.11 on 2026-09-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education')], default='National', max_length=50)),
                ('summary', models.TextField(help_text='Short description shown on the homepage.', max_length=500)),
                ('content', models.TextField(help_text='Rich HTML content from TinyMCE.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
